# Generated by Django 4.1.7 on 2023-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawa', '0004_rename_item_names_product_item_name_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
