# Generated by Django 4.1.7 on 2023-04-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawa', '0006_rename_received_product_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
